[package]
name = "render-engine-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
bitflags = "2"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }

[features]
default = ["vulkan"]
vulkan = ["dep:ash"]

[dependencies.ash]
version = "0.38"
optional = true
default-features = true
